[package]
name = "rp2040-pwm-timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rp2040-hal = "^0.7.0"
fugit-timer = "^0.1.3"
fugit = "^0.3.3"
nb = "^1.0.0"